import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    // flexDirenction:'row',
    justifyContent: 'space-between',
    alignContent: 'center',
    backgroundColor: '#f50',
  },
  backgroundStyle: {
    color: 'red',
    backgroundColor: '#000',
    fontSize: 19,
  },
  textStyle: {
    color: '#fff',
    fontSize: 30,
    textAlign: 'center',
  },
  header: {
    flex: 2,
    alignContent: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderRadius: 10,
    backgroundColor: '#456',
  },
  main: {
    flex: 5,
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'space-between',
    borderWidth: 2,
    borderRadius: 10,
  },
  side: {
    flex: 2,
    alignContent: 'center',
    backgroundColor: '#000',
  },
  content: {
    flex: 5,
    alignContent: 'center',
    backgroundColor: '#f2323',
  },
  footer: {
    flex: 2,
    alignContent: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderRadius: 10,
    backgroundColor: '#f678',
  },
  button: {
    width: 60,
    height: 60,
    backgroundColor: '#f41',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 40,
    position: 'absolute',
    right: 30,
    bottom: 30,
  },
  buttonText: {color: '#fff', fontSize: 36},
  countText: {
    color: '#000',
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    justifyContent: 'center',
  },
  plusButton: {
    backgroundColor: 'green',
    padding: 5,
    width: 40,
    height: 40,
    borderRadius: 40,
    justifyContent: 'center',
    marginBottom: 10,
  },
  minusButton: {
    backgroundColor: 'red',
    padding: 5,
    width: 40,
    height: 40,
    borderRadius: 40,
    justifyContent: 'center',
    marginTop: 10,
  },
});
